spring:
  profiles:
    include: jwt
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        default_batch_fetch_size: 1000
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

logging:
  level:
    com.y2gcoder.blog: debug
    org.hibernate.sql: info
    org.hibernate.type.descriptor.sql: trace
